[providers]
providers = ["node"]

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
WRANGLER_SEND_METRICS = "false"

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
