[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
WRANGLER_SEND_METRICS = "false"

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx wrangler dev --config dist/server/wrangler.json --ip 0.0.0.0 --port ${PORT:-3000} --local"
